name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!console/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            /home/azureuser/deploy-distrikv.sh
